/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:629c1d1b-a19c-469a-bb6a-fd7b15265216",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_VYBr5cRZk",
    "aws_user_pools_web_client_id": "24429g9f7nhmro4ro7u1g2l5dd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://so3bqqcr5fguhh24v7g2l6frf4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-37cj6srnbrehpjzhc7joycxcg4"
};

export default awsmobile;
